--- # Service Module

- hosts        : redhat
  user         : user
  become       : yes
  connection   : ssh
  gather_facts : no

  tasks:
    - name : Install web Server
      yum  : pkg=httpd state=latest
      notify : Restart Apache2 and enable it to start service during reboot.
  handlers :
    - name    : Restart Apache2 and enable it to start service during reboot.
      service : name=httpd state=restarted enabled=yes
