--- # loop example

- hosts: debian
  user : user
  become : yes
  connection : ssh
  gather_facts : no

  tasks : 
   - name : Install Apache service
     apt  : name={{ item }} state=latest
     with_items : 
     - apache2
     notify : Restart Apache Service

  handlers :
   - name     : Restart Apache Service
     service  : name=apache2 state=restarted
