--- # prompt example

- hosts        : redhat
  user         : user
  become       : yes
  connection   : ssh
  gather_facts : no
  
  vars:
    playbook_version : 2.0

  vars_prompt:
   - name    : pkgtoinstall
     prompt  : Package to Install ?
     default : telnet
  tasks : 
    - name   : Installing Package 
      yum    : pkg={{ pkgtoinstall }} state=latest
