--- # tags example

- hosts        : redhat
  user         : user
  become       : yes
  connection   : ssh
  gather_facts : no

  tasks : 
   - name    : Install telnet package
     yum     : pkg={{ item }} state=latest
     with_items : 
      - telnet
      - lynx 
     tags    : packages
   - name    : Query telnet package
     raw     : yum list installed | grep telnet >> /home/user/packages.log
     tags    : logging
